stages:
  - test

variables:
  NEWMAN_BIN: /usr/local/bin/newman

before_script:
  - apt-get update && apt-get install -y curl gnupg
  - curl -sL https://deb.nodesource.com/setup_16.x | bash -
  - apt-get install -y nodejs
  - npm install -g newman

postman_tests:
  stage: test
  script:
    - newman run postman/EjemploJose.postman_collection.json
  
  only:
    - main